// Skills and sub-skills data
export const mainSkills = [
  "Administração, Gestão e Negócios",
  "Agropecuária e Desenvolvimento Rural",
  "Arquitetura, Urbanismo e Design de Interiores",
  "Ciências Fundamentais e Humanidades",
  "Comunicação, Marketing e Publicidade",
  "Contabilidade e Controladoria",
  "Cultura, Artes e Entretenimento",
  "Direito e Legislação",
  "Educação e Pedagogia",
  "Economia e Finanças",
  "Engenharia e Infraestrutura",
  "Meio Ambiente e Sustentabilidade",
  "Políticas Públicas e Ciências Sociais",
  "Relações Internacionais e Comércio Exterior",
  "Saúde e Bem-Estar",
  "Segurança Pública e Defesa",
  "Tecnologia e Inovação",
  "Turismo e Hospitalidade",
  "Outro"
];

export const behavioralSkills = [
  "Adaptabilidade",
  "Analítico",
  "Aprendizagem Contínua",
  "Autonomia",
  "Comunicação",
  "Criatividade",
  "Empatia",
  "Inovação",
  "Inteligência Emocional",
  "Liderança",
  "Minuciosidade",
  "Mobilização",
  "Negociação",
  "Networking",
  "Organização",
  "Orientação para Resultados",
  "Pensamento Crítico",
  "Planejamento",
  "Proatividade",
  "Resiliência",
  "Trabalho em Equipe"
];

export const languages = [
  "Português", "Inglês", "Espanhol", "Francês", "Alemão", "Italiano",
  "Holandês", "Sueco", "Norueguês", "Dinamarquês", "Polonês", "Tcheco",
  "Eslovaco", "Russo", "Ucraniano", "Romeno", "Grego", "Turco", "Árabe",
  "Hebraico", "Persa (Farsi)", "Hindi", "Urdu", "Japonês", "Coreano",
  "Chinês (Mandarim)"
];

export const subSkillsMap: Record<string, string[]> = {
  "Administração, Gestão e Negócios": [
    "Análise de Dados e Business Intelligence",
    "Balanced Scorecard",
    "Business Process Management (BPM)",
    "Compliance e Auditoria Interna",
    "Customer Success e Gestão de Experiência do Cliente",
    "Elaboração de Planos de Negócios",
    "Empreendedorismo e Inovação",
    "Finanças Corporativas",
    "Governança Corporativa",
    "Gestão da Inovação e Metodologias de Inovação",
    "Gestão da Mudança",
    "Gestão de Conflitos",
    "Gestão de Contratos",
    "Gestão de Fornecedores e Cadeia de Suprimentos",
    "Gestão de Operações e Logística",
    "Gestão de Pessoas / Recursos Humanos",
    "Gestão de Projetos",
    "Gestão de Relacionamento com o Cliente (CRM)",
    "Gestão de Riscos e Crises",
    "Gestão de Stakeholders",
    "Gestão de Tempo e Produtividade",
    "Gestão de TI e Sistemas Empresariais",
    "Gestão de Vendas e Negociação",
    "Marketing e Branding",
    "Planejamento Estratégico",
    "Precificação e Revenue Management",
    "Qualidade e Processos",
    "Sustentabilidade e Responsabilidade Social",
    "Outro"
  ],

  "Agropecuária e Desenvolvimento Rural": [
    "Agroecologia e Produção Orgânica",
    "Agroindústria e Processamento de Alimentos",
    "Agronomia Geral",
    "Análise e Melhoria de Solo",
    "Apicultura",
    "Armazenamento e Logística de Grãos",
    "Assistência Técnica e Extensão Rural",
    "Biotecnologia Agrícola",
    "Cadeias Produtivas e Cooperativismo",
    "Comercialização e Marketing Agropecuário",
    "Controle de Pragas e Doenças",
    "Desenvolvimento Territorial e Políticas Agrícolas",
    "Economia Rural e Análise de Mercados",
    "Fertilização e Nutrição de Plantas",
    "Gestão de Recursos Hídricos",
    "Irrigação e Drenagem",
    "Mecanização Agrícola",
    "Melhoramento Genético Vegetal e Animal",
    "Piscicultura e Aquicultura",
    "Produção Animal",
    "Produção Vegetal",
    "Reflorestamento e Silvicultura",
    "Regularização Fundiária e Reforma Agrária",
    "Segurança Alimentar e Sistemas Alimentares Sustentáveis",
    "Sistemas Agroflorestais",
    "Sustentabilidade e Conservação Ambiental",
    "Tecnologia de Alimentos e Agroindústria",
    "Zootecnia e Nutrição Animal",
    "Outro"
  ],

  "Arquitetura, Urbanismo e Design de Interiores": [
    "Acústica e Isolamento Térmico",
    "Acessibilidade e Desenho Universal",
    "Arquitetura de Interiores e Mobiliário",
    "Arquitetura Modular e Off-site",
    "Arquitetura Paisagística e Paisagismo",
    "BIM e Modelagem Paramétrica",
    "Conforto Ambiental e Eficiência Energética",
    "Conservação, Restauração e Patrimônio Arquitetônico e Cultural",
    "Coordenação e Compatibilização de Projetos",
    "Design Biofílico",
    "Design de Móveis e Produtos",
    "Desenho Urbano e Planejamento Urbano",
    "Docência e Pesquisa em Arquitetura",
    "Gestão de Projetos de Arquitetura e Urbanismo",
    "Iluminação e Projeto Luminotécnico",
    "Legislação Urbanística e Normas Técnicas",
    "Logística e Gestão de Resíduos em Obras",
    "Materiais e Tecnologias Construtivas",
    "Orçamentação e Acompanhamento de Obras",
    "Participatory Design",
    "Renderização e Visualização 3D",
    "Sustentabilidade em Projetos",
    "Urbanismo e Desenvolvimento de Cidades",
    "Urbanismo Tático e Mobilidade Urbana",
    "Vistoria e Perícia em Edificações",
    "Outro"
  ],

  "Ciências Fundamentais e Humanidades": [
    "Antropologia e Arqueologia",
    "Astrofísica e Cosmologia",
    "Bioquímica e Biologia Molecular",
    "Biologia Geral e Ecologia Fundamental",
    "Ciências da Linguagem e Linguística",
    "Ciências da Religião e Teologia",
    "Ciências do Comportamento e Psicologia Experimental",
    "Criminologia e Estudos Forenses",
    "Estatística e Probabilidade",
    "Estudos Culturais e Estudos de Gênero",
    "Física",
    "Filosofia",
    "Geografia Humana e Regional",
    "Geologia e Paleontologia",
    "História",
    "Lógica e Fundamentos da Matemática",
    "Matemática",
    "Metodologias de Pesquisa Acadêmica",
    "Neurociência",
    "Química",
    "Sociologia e Teoria Social",
    "Zoologia e Botânica",
    "Outro"
  ],

  "Comunicação, Marketing e Publicidade": [
    "Assessoria de Imprensa e Relações Públicas",
    "Brand Journalism/Branded Content",
    "Branding e Gestão de Marcas",
    "Captação de Vídeo",
    "Comunicação Estratégica",
    "Content Marketing e Estratégia de Conteúdo",
    "Copywriting e Publicidade Criativa",
    "Design Gráfico e Direção de Arte",
    "Edição de Vídeo",
    "E-mail Marketing e Automação",
    "Engajamento e Gestão de Comunidades Online",
    "Fotografia e Edição Fotográfica",
    "Gamification e Engajamento Digital",
    "Gerenciamento de Reputação Online",
    "Gestão de Crises e Comunicação de Risco",
    "Gestão de Eventos e Ativações de Marca",
    "Gestão de Podcast e Conteúdo em Áudio",
    "Growth Copywriting ou UX Writing",
    "Growth Marketing/Growth Hacking",
    "Jornalismo Cultural",
    "Jornalismo Digital e Multimídia",
    "Jornalismo Econômico",
    "Jornalismo Esportivo",
    "Jornalismo Investigativo",
    "Jornalismo Político",
    "Marketing de Experiência",
    "Marketing de Influência",
    "Marketing de Performance e Otimização de Conversão (CRO)",
    "Marketing Digital e Estratégias Online",
    "Marketing Mobile",
    "Marketing Político e Campanhas Eleitorais",
    "Media Training",
    "Mídia Paga e Planejamento de Mídia",
    "Mídia Programática e Inovação em Dados",
    "Pesquisa de Mercado e Análise de Público",
    "Produção Audiovisual e Conteúdo Multimídia",
    "Publicidade Programática e Inovação Tecnológica",
    "Redação Publicitária e Jornalística",
    "SEO e Marketing de Conteúdo",
    "Social Media e Gestão de Redes Sociais",
    "Storytelling e Data Storytelling",
    "Web Analytics e Métricas de Desempenho",
    "Outro"
  ],

  "Contabilidade e Controladoria": [
    "Análise de Custos e Formação de Preços",
    "Análise de Demonstrações Financeiras",
    "Análise de Indicadores Financeiros e KPIs",
    "Análise de Investimentos e Valuation",
    "Auditoria Externa",
    "Auditoria Forense e Investigação de Fraudes",
    "Auditoria Interna e Controles",
    "Avaliação e Gestão de Ativos Intangíveis",
    "Balanced Scorecard e Controladoria Estratégica",
    "Business Intelligence em Contabilidade",
    "Compliance e Governança Corporativa",
    "Conciliação Contábil e Bancária",
    "Contabilidade de Custos e Gerencial",
    "Contabilidade de Hedge e Derivativos",
    "Contabilidade e Tributação de Criptomoedas/Ativos Digitais",
    "Contabilidade Geral e Avançada",
    "Contabilidade Governamental e do Terceiro Setor",
    "Contabilidade Internacional",
    "Contabilidade Tributária e Planejamento Fiscal",
    "Controladoria de Projetos e Processos",
    "Demonstrações Contábeis e Relatórios Gerenciais",
    "Due Diligence",
    "Gestão de Fluxo de Caixa e Capital de Giro",
    "Gestão de Orçamento e Planejamento Financeiro",
    "Gestão de Riscos Financeiros",
    "Implementação de IFRS em Startups e PMEs",
    "Modelagem Financeira e Forecasting",
    "Normas Contábeis e Regulamentação",
    "Planejamento Sucessório e Patrimonial",
    "Sistemas de Informação Contábil e ERP",
    "Softwares Contábeis e Ferramentas Digitais",
    "Técnicas de Valuation e Análise de Investimentos",
    "Outro"
  ],

  "Cultura, Artes e Entretenimento": [
    "Animação e Motion Graphics",
    "Arquitetura Cênica e Cenografia",
    "Arte Interativa e Multimídia",
    "Artesanato e Produção Manual",
    "Crítica Cultural e Jornalismo Especializado",
    "Curadoria Cultural e Exposições",
    "Design Gráfico e Direção de Arte",
    "Direção de Fotografia e Produção Audiovisual",
    "Edição de Vídeo e Pós-produção",
    "Fotografia e Edição Fotográfica",
    "Figurino e Produção de Indumentárias",
    "Gestão Cultural e Políticas Culturais",
    "Games e Gamificação Cultural",
    "Ilustração e Arte Digital",
    "Iluminação Cênica",
    "Montagem e Elaboração de Projetos Culturais",
    "Moda e Produção de Moda",
    "Performance Arte e Arte de Rua",
    "Produção Audiovisual",
    "Produção de Circo e Artes Circenses",
    "Produção de Conteúdo Digital",
    "Produção Editorial e Literária",
    "Produção de Eventos Culturais e Entretenimento",
    "Produção Musical e Sonora",
    "Sonoplastia, Edição de Áudio e Trilha Sonora",
    "Teatro e Artes Cênicas",
    "Outro"
  ],

  "Direito e Legislação": [
    "Advocacy",
    "Assessoria Jurídica e Consultoria Legal",
    "Compliance e Governança Corporativa",
    "Criminal Compliance",
    "Direito Administrativo",
    "Direito Ambiental",
    "Direito Civil e Processual Civil",
    "Direito Comparado",
    "Direito Constitucional",
    "Direito Desportivo",
    "Direito Digital e de Tecnologia",
    "Direito do Consumidor",
    "Direito Eleitoral",
    "Direito Empresarial",
    "Direito Internacional",
    "Direito Penal e Processual Penal",
    "Direito Previdenciário",
    "Direito Processual",
    "Direito Sanitário",
    "Direito do Trabalho e Sindical",
    "Direito Tributário e Fiscal",
    "Elaboração de Minutas e Contratos",
    "Elaboração de Pareceres Jurídicos",
    "Magistratura",
    "Mediação, Arbitragem e Solução de Conflitos",
    "Ministério Público",
    "Pesquisa Jurídica e Doutrinária",
    "Privacidade e Proteção de Dados (LGPD/GDPR)",
    "Propriedade Intelectual e Direito Autoral",
    "Regulação e Normas Regulatórias",
    "Técnicas de Negociação e Advocacia",
    "Técnicas de Redação Jurídica",
    "Técnicas de Redação Legislativa",
    "Treinamento e Capacitação em Direito",
    "Outro"
  ],

  "Educação e Pedagogia": [
    "Alfabetização e Letramento",
    "Andragogia (Educação de Adultos)",
    "Avaliação Educacional e Instrumentos de Avaliação",
    "Currículo e Planejamento Pedagógico",
    "Educação de Jovens e Adultos (EJA)",
    "Educação Inclusiva e Diversidade",
    "Educação Infantil e Pré-Escolar",
    "Ensino Fundamental",
    "Ensino Médio",
    "Ensino Médio Técnico",
    "Ensino Superior e Pesquisa Acadêmica",
    "Formação e Capacitação Docente",
    "Gestão Escolar e Administrativa",
    "Mentoria Educacional",
    "Metodologias Ativas e Inovação Pedagógica",
    "Orientação Pedagógica",
    "Orientação Profissional e de Carreiras",
    "Políticas Educacionais e Gestão de Projetos",
    "Tecnologias Digitais e Recursos Multimídia na Educação",
    "Teorias da Aprendizagem e Desenvolvimento Humano",
    "Tutoria em Sala de Aula",
    "Outro"
  ],

  "Economia e Finanças": [
    "Análise de Investimentos e Valuation",
    "Análise Fundamentalista e Técnica de Ações",
    "Análise Macroeconômica e Cenários Econômicos",
    "Análise de Impacto Econômico e Estudos de Viabilidade",
    "Auditoria Financeira",
    "Bancos e Mercado Financeiro",
    "Controladoria e Custos",
    "Derivativos e Produtos Estruturados",
    "Economia Comportamental",
    "Economia da Saúde e Educação",
    "Economia Digital e Plataformas Online",
    "Economia e Finanças Públicas",
    "Economia do Setor Público",
    "Economia Internacional e Comércio Exterior",
    "Economia Regional e Urbana",
    "Finanças Pessoais",
    "Gestão de Ativos e Portfólios",
    "Gestão de Orçamento e Planejamento Financeiro",
    "Gestão de Riscos Financeiros",
    "Governança e Compliance Financeira",
    "Investimentos Alternativos (Private Equity, Venture Capital)",
    "Mercado de Capitais e Tesouraria",
    "Microeconomia e Políticas de Preço",
    "Modelagem Econômica e Econometria",
    "Orçamento Público e Lei de Responsabilidade Fiscal",
    "Planejamento Tributário e Fiscal",
    "Precificação de Ativos e Avaliação Econômica de Projetos",
    "Relações com Investidores",
    "Startups e Fintechs",
    "Trade Finance e Câmbio",
    "Outro"
  ],

  "Engenharia e Infraestrutura": [
    "Análise de Impacto Ambiental e Viabilidade Técnica",
    "Automação Industrial e Sistemas de Controle",
    "Automação Predial e Smart Buildings",
    "Cartografia, Topografia e Georreferenciamento",
    "Confiabilidade e Manutenção Industrial",
    "Construção Civil e Edificações",
    "Desenho Técnico, CAD e Modelagem 3D",
    "Engenharia Agrícola e Irrigação",
    "Engenharia Ambiental e Sustentabilidade",
    "Engenharia de Materiais e Metalurgia",
    "Engenharia de Minas e Geotecnia",
    "Engenharia de Petróleo e Gás",
    "Engenharia de Produção e Lean Manufacturing",
    "Engenharia de Segurança do Trabalho",
    "Engenharia Elétrica",
    "Engenharia Eletrônica e Telecomunicações",
    "Engenharia Forense e Perícias Técnicas",
    "Engenharia Mecânica e Mecatrônica",
    "Engenharia Química e Processos Industriais",
    "Ferramentas BIM (Building Information Modeling)",
    "Geotecnia Ambiental e Contenção de Áreas Contaminadas",
    "Gestão de Infraestrutura e Facilities",
    "Gestão de Obras Públicas e Contratos de Engenharia",
    "Gestão de Projetos de Infraestrutura",
    "Hidráulica e Recursos Hídricos",
    "Infraestrutura de Transportes (Rodovias, Ferrovias, Portos, Aeroportos)",
    "Internet das Coisas (IoT) em Engenharia",
    "Licenciamento Ambiental e Gestão de Impactos",
    "Planejamento Urbano e Regional",
    "Simulação Computacional e Prototipagem Virtual",
    "Sistemas Prediais (Elétricos, Hidráulicos, Sanitários)",
    "Tecnologia e Inovação em Engenharia",
    "Termodinâmica e Transferência de Calor",
    "Outro"
  ],

  "Meio Ambiente e Sustentabilidade": [
    "Análise de Ciclo de Vida (ACV)",
    "Auditoria Ambiental e Certificações",
    "Biodiversidade e Conservação de Ecossistemas",
    "Bioenergia e Energias Renováveis",
    "Economia Ambiental e Valoração de Recursos Naturais",
    "Economia Circular e Gestão de Resíduos",
    "Educação Ambiental e Sensibilização",
    "Gestão de Bacias Hidrográficas",
    "Gestão de Emissões de Gases de Efeito Estufa (GEE)",
    "Gestão de Recursos Hídricos e Saneamento",
    "Gestão de Riscos Ambientais e Planos de Contingência",
    "Gestão de Unidades de Conservação",
    "Impactos Ambientais e Licenciamento",
    "Legislação Ambiental e Políticas Públicas",
    "Monitoramento e Controle da Poluição",
    "Pagamentos por Serviços Ambientais",
    "Planejamento Ambiental Urbano e Regional",
    "Planejamento e Gestão de Áreas Protegidas",
    "Recuperação de Áreas Degradadas",
    "Sensoriamento Remoto e Geoprocessamento Ambiental",
    "Sistemas Agroflorestais e Agroecologia",
    "Soluções Baseadas na Natureza",
    "Tecnologias Limpas e Inovação Ambiental",
    "Turismo Sustentável e Ecoturismo",
    "Outro"
  ],

  "Políticas Públicas e Ciências Sociais": [
    "Análise de Indicadores e Dados Sociais",
    "Análise de Políticas Setoriais",
    "Antropologia e Etnografia",
    "Avaliação de Eficiência e Impacto de Políticas Públicas",
    "Ciência Política e Teorias do Estado",
    "Desenho e Avaliação de Políticas Públicas",
    "Economia Social e Solidária",
    "Elaboração e Gestão de Parcerias Público-Privadas (PPPs)",
    "Estudos Urbanos e Dinâmicas Metropolitanas",
    "Gestão e Negócios de Impacto Social",
    "Gestão Interfederativa e Consórcios Públicos",
    "Governança e Transparência Pública",
    "Mapeamento e Gestão de Conflitos Sociais",
    "Metodologias de Pesquisa Social",
    "Monitoramento e Avaliação de Projetos Sociais",
    "Movimentos Sociais e Sociedade Civil Organizada",
    "Orçamento Participativo e Planejamento Colaborativo",
    "Planejamento e Gestão de Projetos Públicos",
    "Políticas de Inclusão e Assistência Social",
    "Políticas de Juventude e Desenvolvimento Comunitário",
    "Políticas de Segurança Pública e Justiça Criminal",
    "Relações Internacionais e Cooperação para o Desenvolvimento",
    "Sociologia e Estudos de Cultura",
    "Outro"
  ],

  "Relações Internacionais e Comércio Exterior": [
    "Acordos Comerciais e Negociações Internacionais",
    "Análise de Riscos Geopolíticos e Geoeconômicos",
    "Cadeia de Suprimentos Globais e Logística Internacional",
    "Comércio Exterior e Gestão de Exportação/Importação",
    "Compliance e Regulamentos Internacionais",
    "Defesa e Segurança Internacional",
    "Diplomacia Climática e Acordos Ambientais",
    "Diplomacia Cultural e Soft Power",
    "Diplomacia Econômica e Política Comercial",
    "Economia Internacional e Integração Regional",
    "Estudos de Blocos Econômicos e Integração Regional",
    "Inteligência Comercial e Mapeamento de Oportunidades",
    "Marketing Internacional",
    "Mediação de Disputas Internacionais e Arbitragem",
    "Mercado Cambial e Financiamentos Internacionais",
    "Negociação Intercultural",
    "Negociações Diplomáticas e Relações Bilaterais/Multilaterais",
    "Organismos Internacionais",
    "Política Externa e Geopolítica",
    "Políticas de Cooperação e Ajuda ao Desenvolvimento",
    "Protocolo e Cerimonial Internacional",
    "Regimes de Comércio, Barreiras Tarifárias e Não Tarifárias",
    "Relações Governamentais",
    "Resiliência e Ajuda Humanitária",
    "Sustentabilidade e Ética no Comércio Global",
    "Tratados Internacionais e Direito Internacional",
    "Outro"
  ],

  "Saúde e Bem-Estar": [
    "Anestesiologia",
    "Atenção Primária à Saúde",
    "Bioética e Ética em Saúde",
    "Biossegurança e Controle de Infecções",
    "Cardiologia",
    "Cirurgia Geral",
    "Clínica Médica",
    "Dermatologia",
    "Educação em Saúde e Comunicação de Riscos",
    "Endocrinologia",
    "Enfermagem",
    "Farmácia Clínica e Manipulação",
    "Farmacovigilância e Assistência Farmacêutica",
    "Fisioterapia e Reabilitação",
    "Fitoterapia e Medicina Integrativa",
    "Fonoaudiologia",
    "Gastroenterologia",
    "Geriatria",
    "Gerontologia e Cuidados Paliativos",
    "Gestão de Planos de Saúde e Auditoria",
    "Gestão e Políticas de Saúde",
    "Hematologia",
    "Infectologia",
    "Inovações em Biotecnologia e Saúde Digital",
    "Medicina da Família e Comunidade",
    "Nefrologia",
    "Neurologia",
    "Nutrição e Dietética",
    "Odontologia",
    "Oftalmologia",
    "Oncologia",
    "Ortopedia e Traumatologia",
    "Otorrinolaringologia",
    "Pediatria",
    "Pesquisa Clínica e Bioestatística",
    "Pneumologia",
    "Práticas Integrativas e Complementares",
    "Psiquiatria",
    "Qualidade e Segurança do Paciente",
    "Reumatologia",
    "Saúde Coletiva e Promoção da Saúde",
    "Saúde de Populações Indígenas, Quilombolas e Minorias",
    "Saúde Mental e Psicologia",
    "Saúde Ocupacional e Ergonomia",
    "Saúde Pública e Epidemiologia",
    "Telemedicina e Inovação em Saúde",
    "Terapia Ocupacional",
    "Urologia",
    "Veterinária",
    "Vigilância Sanitária e Epidemiológica",
    "Outro"
  ],

  "Segurança Pública e Defesa": [
    "Analista Criminal e Inteligência Policial",
    "Antiterrorismo e Contraterrorismo",
    "Aplicação de Drones e Robótica em Segurança",
    "Atuação em Policiamento Comunitário",
    "Ciências Forenses e Perícia Criminal",
    "Combate a Crimes Cibernéticos",
    "Controle de Armas e Munições",
    "Coordenação Multidisciplinar com Políticas Sociais",
    "Defesa Civil e Gerenciamento de Desastres",
    "Estratégia e Logística Militar",
    "Fronteiras e Migração",
    "Gestão e Administração de Instituições de Segurança",
    "Gestão de Crises e Operações Táticas",
    "Gestão Prisional e Reinserção Social",
    "Inteligência e Contrainteligência de Estado",
    "Mediação de Conflitos e Pacificação Social",
    "Operações Especiais e Táticas Avançadas",
    "Planejamento e Políticas de Segurança Pública",
    "Prevenção à Violência e Criminalidade",
    "Relações Internacionais e Segurança Global",
    "Resgate e Atendimento Pré-Hospitalar (APH)",
    "Segurança Cibernética",
    "Segurança de Infraestrutura Crítica",
    "Segurança Institucional e Proteção de Autoridades",
    "Sistemas de Comando e Controle",
    "Tecnologias de Vigilância e Monitoramento",
    "Outro"
  ],
  
  "Tecnologia e Inovação": [
    "Análise de Dados e Business Intelligence",
    "Arquitetura de Software",
    "Automação Industrial e Robótica",
    "Blockchain e Criptomoedas",
    "Cibersegurança",
    "Ciência de Dados e Machine Learning",
    "Cloud Computing e Virtualização",
    "DataOps e MLOps",
    "Design Thinking e Metodologias de Inovação",
    "Desenvolvimento Back-end",
    "Desenvolvimento de Aplicativos Móveis",
    "Desenvolvimento Front-end",
    "Desenvolvimento Full-stack",
    "DevOps e Integração Contínua/Entrega Contínua (CI/CD)",
    "Edge Computing",
    "Gestão de Produtos Digitais",
    "Gestão de Projetos de TI",
    "Inteligência Artificial",
    "Internet das Coisas (IoT)",
    "Metaverso e Realidade Virtual/Aumentada",
    "Microservices e Arquitetura de Sistemas Distribuídos",
    "Redes e Telecomunicações",
    "Segurança da Informação",
    "Testes de Software e Garantia de Qualidade (QA)",
    "Transformação Digital e Cultura de Inovação",
    "UX/UI Design",
    "Web3 e Smart Contracts",
    "Outro"
  ],

  "Turismo e Hospitalidade": [
    "Agenciamento de Viagens e Operadoras",
    "Análise de Dados e Inteligência Turística",
    "Atendimento e Hospitalidade",
    "Auditoria e Controle de Qualidade em Serviços",
    "Ecoturismo e Turismo de Aventura",
    "Eventos e Congressos",
    "Gastronomia e Enologia",
    "Gestão de Contas Corporativas",
    "Gestão de Destinos Turísticos",
    "Gestão de Facilities e Operações Hoteleiras",
    "Gestão de Restaurantes e Serviços de Alimentos",
    "Guias e Intérpretes de Turismo",
    "Inovação em Hospitalidade e Serviços",
    "Marketing Turístico e Promoção de Destinos",
    "Planejamento e Desenvolvimento Turístico",
    "Protocolo e Cerimonial",
    "Qualidade e Fidelização do Cliente",
    "Revenue Management e Tarifação",
    "Roteiros Temáticos e Turismo Cultural",
    "Tecnologias e Plataformas de Reserva",
    "Turismo Acessível e Inclusivo",
    "Turismo de Bem-Estar e Saúde",
    "Turismo de Luxo",
    "Turismo de Negócios e Eventos Corporativos",
    "Turismo Religioso",
    "Turismo Rural e Comunitário",
    "Turismo Sustentável e Responsável",
    "Turismo Virtual e Realidade Aumentada",
    "Outro"
  ]
};
